Website = "https://github.com/bytemystery-com/smartdiary"

[Details]
Icon = "assets/icons/icon.png"
Name = "SmartDiary"
ID = "com.bytemystery.smartdiary2"
Version = "0.3.5"
Build = 247

[LinuxAndBSD]
GenericName = "SmartDiary"
Categories = ["Education"]
Comment = "SmartDiary"
Keywords = ["diary"]
