Website = "https://github.com/bytemystery-com/smartdiary"

[Details]
Icon = "assets/icons/icon.png"
Name = "SmartDiary"
ID = "com.bytemystery.smartdiary2"
Version = "0.4.2"
Build = 277

[LinuxAndBSD]
GenericName = "SmartDiary"
Categories = ["Education"]
Comment = "SmartDiary"
Keywords = ["diary"]

[Migrations]
fyneDo = true
