[Details]
Icon = "assets/icons/icon.png"
Name = "SmartDiary"
ID = "com.bytemystery.smartdiary2"
Version = "0.3.3"
Build = 209

[LinuxAndBSD]
GenericName = "SmartDiary"
Categories = ["Education"]
Comment = "SmartDiary"
Keywords = ["diary"]
